server:
  port: 6969

spring:
  application:
    name: llm.connector.gateway
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    username: postgres
    password: 123edc#EDC
    url: jdbc:postgresql://122.185.239.46:5432/ds-llm-connector-gateway?useSSL=false&stringtype=unspecified
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
    #Used for single open AI configuration. (Only for testing will remove it)
  ai:
    openai:
      api-key: ashar581
      base-url: http://localhost:8080
      chat:
        completions-path: /v1/chat/completions
        options:
          model: qwen2.5-7b-instruct-q4_0-00001-of-00002.gguf
          temperature: 0.7

app:
  security:
    key:
      signing-secret: fe80::6184:62f1:2b9e:5b8313:8666:1qaz
      key-type: shared
      use-env: false
      key-env-var: secret

llm:
  sources:
    free:
      models:
        - id: qwen-instruct
          type:
            - chat
            - agent
            - summarization
            - generation
            - tool
            - rag
          base-url: http://localhost:8080
          api-path: /v1/chat/completions
          api-key: ashar581
          port: 8080
          model-name: qwen2.5-7b-instruct-q4_0-00001-of-00002.gguf
          mm-proj :
          context: 16000
          parallelExecution: 4
          active: true

        - id: bonsai
          type:
            - chat
            - agent
            - summarization
            - generation
            - rag
          base-url: http://localhost:8082
          api-path: /v1/chat/completions
          api-key: ashar581
          port: 8082
          model-name: Bonsai-8B.gguf
          mm-proj :
          context: 16384
          parallelExecution: 8
          active: true

        - id: qwen-coder
          type:
            - code
          base-url: http://localhost:8083
          api-path: /v1/chat/completions
          api-key: ashar581
          port: 8083
          model-name: qwen2.5-coder-7b-instruct-q4_k_m.gguf
          mm-proj :
          context: 8192
          parallelExecution: 1
          active: false

        - id: qwen-vl
          type:
            - vision
            - classification
          base-url: http://localhost:8084
          api-path: /v1/chat/completions
          api-key: ashar581
          port: 8084
          model-name: Qwen_Qwen2.5-VL-7B-Instruct-Q2_K_L.gguf
          mm-proj : mmproj-Qwen_Qwen2.5-VL-7B-Instruct-f16.gguf
          context: 8192
          parallelExecution: 1
          active: true

        - id: qwen-sml
          type:
            - chat
            - agent
            - summarization
            - generation
            - tool
            - rag
          base-url: http://localhost:8085
          api-path: /v1/chat/completions
          api-key: ashar581
          port: 8085
          model-name: Qwen3.5-4B-Q4_K_M.gguf
          mm-proj :
          context: 4096
          parallelExecution: 2
          active: false

        - id: bge-large-embed
          type:
            - embedding
          base-url: http://localhost:9090
          api-path: /v1/embeddings
          api-key: ashar581
          port: 9090
          model-name: bge-large-en-v1.5-q4_k_m.gguf
          mm-proj :
          context: 8192
          parallelExecution: 4
          active: false

        - id: qwen3-embed
          type:
            - embedding
          base-url: http://localhost:9091
          api-path: /v1/embeddings
          api-key: ashar581
          port: 9091
          model-name: Qwen3-Embedding-8B-Q4_K_M.gguf
          mm-proj :
          context: 8192
          parallelExecution: 2
          active: false
    paid:
      models:
        - id: openai-gpt4
          type:
            - chat
            - agent
            - summarization
            - generation
          provider: openai
          api-key: ashar581
          model-name: gpt-4o

        - id: openai-embed
          type:
            - embedding
          provider: openai
          api-key: ashar581
          model-name: text-embedding-3-large